### ISSUE TITLE
Certificate should not be included in image as it's a security risk

### ISSUE THREAD

**Issue by juhovan** [imTHAI/docker-pixelserv-tls#2]
Currently the built image contains a CA certificate from build time and by following README user will use the included certificate.
Therefore all instances that are set up using the README are sharing the same CA key and certificate that is public.
This is terrible because if the user decides to trust this CA certificate any device with the cert can be MITM'd.

The image absolutely should not include a CA key/crt and it should be generated in an entrypoint script unless it already exists.
This way user can mount a volume to /var/cache/pixelserv/ and a permanent unique CA certificate will be automatically generated.

This can be verified by running: `docker run --entrypoint sh imthai/pixelserv-tls -c 'apk add openssl >/dev/null && openssl x509 -in /var/cache/pixelserv/ca.crt -noout -modulus'`
Which will always, even on another machine, return the same modulus for same build of this image.

For image id 5188c3004f6c the modulus will be `Modulus=D3480CE2D5484D4DDC5C4931B33EB293762D2EBF2A6B4A46FFFFAA451678ACC297AC77A72203DCA7A3D9FBDFCE4875364824A7546DF427902210F18E0B05DA68F28E4BBE8AA7E8796EDE180E20CF7299661BCC79CD34B1CF476F537311A1C0F8F1E8C8FEC28E919B1AA497D8803CFA59A6A56BEE096A2E59EFEFDAB2F142AC0189005AB6066A27114B7F69CD40D4DED91B0EFAD17C0BFF33DF1CADC5B1657161ADB955377DDA55CCEFBA6088FAAB560198440EBC11A2D2F23DB3C6C888FCB9B45EB7F60B182F35A2385ADA93FE4AB251465BC481F888DC2E4B21B1A7B441A77713813A84BE2D004F92DBB84A2F096CA6CD455049084518E75A18E007919A394D`

**Comment by imTHAI** [comment]
Hello,

Fair point.
I'll think to add a generating script when I have time.
In the meantime, paranoiac people can just generate their own pair of certificate files and replace the original ones. It'll take one command.
